[package]
name = "ffi"
version = "0.1.0"
authors = ["gustin <gustin@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
ed25519-dalek = "1.0.0-pre.1"
rand = "*"
rocksdb = "0.12.4"
qrcodegen = "1.5.0"
slauth = "0.4.4"


